version : 0.1

phases:
  build:
    commands:
      - echo "Building the project..."
      - npm run build
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 sync ./ s3://myshoppingappbucket

artifacts:
  files:
    - '**/*'
  base-directory: '.'

